apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-headless-client-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-headless-client-sidecar
  template:
    metadata:
      labels:
        app: tg-headless-client-sidecar
    spec:
      containers:
        - name: main-container
          image: ubuntu:latest
          command: [ "/bin/sh","-c" ]
          args:
            - apt-get update;
              sleep infinity;
        - name: sidecar-container
          image: ubuntu:latest
          securityContext:
            privileged: true
          command: ["/bin/sh","-c"]
          args:
            - apt-get update;
              apt-get install curl -y;
              curl https://binaries.twingate.com/client/linux/install.sh | bash;
              sudo twingate setup --headless /etc/twingate-service-key/key.base64;
              sudo twingate start;
              sleep infinity;
          volumeMounts:
            - mountPath: "/etc/twingate-service-key/"
              name: service-key
              readOnly: true
      volumes:
        - name: service-key
          secret:
            secretName: service-key